INSERT INTO products (price, category, description, image, name) VALUES (4000, "combos / salmon", "15 pieces of Sake, Cream Roll, Salmon Maki, Feel Roll", "www.imagen.com/salmonx15", "Full Salmon X15");
INSERT INTO products (price, category, description, image, name) VALUES (7800, "combos / salmon", "30 pieces of Sake, Cream Roll, Salmon Maki, Feel Roll, Tropical, SPF", "www.imagen.com/salmonx30", "Full Salmon X30");
INSERT INTO products (price, category, description, image, name) VALUES (9700, "combos / salmon", "45 pieces of Sake, Cream Roll, Salmon Maki, Feel Roll, Tropical, SPF, Geisha, Nigiri, Sashimi", "www.imagen.com/salmonx45", "Full Salmon X45");
INSERT INTO products (price, category, description, image, name) VALUES (3900, "combos / cooked", "15 pieces of Hot Roll, Poshi, Spicy", "www.imagen.com/cookedx15", "Cooked X15");
INSERT INTO products (price, category, description, image, name) VALUES (7450, "combos / cooked", "30 pieces of Hot Roll, Poshi, Spicy, Ebi", "www.imagen.com/cookedx15", "Cooked X30");
INSERT INTO products (price, category, description, image, name) VALUES (9400, "combos / cooked", "45 pieces of Hot Roll, Poshi, Spicy, Ebi, Kani Roll", "www.imagen.com/cookedx15", "Cooked X45");
INSERT INTO products (price, category, description, image, name) VALUES (6900, "combos / cooked", "25 pieces breaded in Panko and Tempura, includes Poshi, Maki Crazy, Veggie Crunch, California Tori, Guacamole Roll", "www.imagen.com/cookedx15", "Crispy X25");
INSERT INTO products (price, category, description, image, name) VALUES (4000, "combos / veggie", "20 pieces of Pepper Roll, Mango Roll, Maki Veggie, Veggie Crunch", "www.imagen.com/cookedx15", "Veggie X20");
INSERT INTO products (price, category, description, image, name) VALUES (3800, "combos / single", "The Single Combo includes 10 pieces of the chef's choice, 1 Gyoza and a soda", "www.imagen.com/cookedx15", "Single Combo");
INSERT INTO products (price, category, description, image, name) VALUES (7600, "combos / tasting", "30 pieces of Sake, Feel Roll, Tropical Roll, Spicy, Poshi, Hot Roll, Mango Roll, Pepper Roll", "www.imagen.com/cookedx15", "Tasting Combo X30");
INSERT INTO products (price, category, description, image, name) VALUES (9500, "combos / tasting", "45 pieces of Sake, Feel Roll, Tropical Roll, Spicy, Poshi, Hot Roll, Mango Roll, Pepper Roll", "www.imagen.com/cookedx15", "Tasting Combo X45");
INSERT INTO products (price, category, description, image, name) VALUES (7900, "combos / rnr", "30 pieces of Koi, Rock and Roll, Tobiko, Avocado, Hot Roll, Soul, Pepper Roll", "www.imagen.com/cookedx15", "Rock and Roll X30");
INSERT INTO products (price, category, description, image, name) VALUES (10200, "combos / rnr", "45 pieces of Koi, Rock and Roll, Tobiko, Avocado, California Tori, Soul, Ebi Cream, Veggie Crunch, Koi", "www.imagen.com/cookedx15", "Rock and Roll X45");
INSERT INTO products (price, category, description, image, name) VALUES (10200, "combos / premium", "45 pieces of Tobiko, Avocado, Soul, SPF, Maki Crazy", "www.imagen.com/cookedx15", "Premium X45");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "shrimps, avocado, swiss cheese, palm heart, caramelized almond", "www.imagen.com/cookedx15", "Ebi X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "crispy shrimps, chive, swiss cheese, palm heart, spicy sauce", "www.imagen.com/cookedx15", "Spicy X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "teriyaki chicken, grilled pepper, swiss cheese, avocado, tempura and panko (fried roll)", "www.imagen.com/cookedx15", "Poshi X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "Honey cooked salmon, ginger and species, swiss cheese, chive, fried sweet potato and tare sauce", "www.imagen.com/cookedx15", "Hot Roll X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "Salmon, avocado, swiss cheese, grilled shrimps, bittersweet sauce", "www.imagen.com/cookedx15", "Sake X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "Kanicama, swiss cheese, avocado, black sesame", "www.imagen.com/cookedx15", "Kani Roll X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "black rice, salmon, avocado, crispy shrimps, swiss cheese", "www.imagen.com/cookedx15", "Cream Roll X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "rice, seaweed, salmon", "www.imagen.com/cookedx15", "Maki Salmon X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "tamago, mango, salmon, swiss cheese, sweet potato chips, passion fruit sauce", "www.imagen.com/cookedx15", "Tropical Roll X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "tamago, double swiss cheese, chive", "www.imagen.com/cookedx15", "Feel X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "cucumber, swiss cheese, avocado, cooked carrot", "www.imagen.com/cookedx15", "Maki Veggie X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "black rice, swiss cheese, avocado, mango, sweet potato chips and passion fruit sauce", "www.imagen.com/cookedx15", "Mango Roll X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "grilled pepper, palm heart, swiss cheese, mixed sesame", "www.imagen.com/cookedx15", "Pepper Roll X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "grilled shrimps, avocado, crab salad, seaweed caviar", "www.imagen.com/cookedx15", "Tobiko X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "salmon, avocado, swiss cheese, white sesame", "www.imagen.com/cookedx15", "SPF X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "salmon, chive, swiss cheese, avocado slice", "www.imagen.com/cookedx15", "Avocado X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "crispy shrimps, tampico sauce, swiss cheese, avocado, tempura and panko (fried roll)", "www.imagen.com/cookedx15", "Maki Crazy X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "tamago, salmon, swiss cheese, avocado, palm heart, caramelized almond", "www.imagen.com/cookedx15", "Soul X4");
INSERT INTO products (price, category, description, image, name) VALUES (1200, "rolls", "salmon slice, swiss cheese, avocado", "www.imagen.com/cookedx15", "Geisha X4");
INSERT INTO products (price, category, description, image, name) VALUES (1200, "rolls", "rice, slice of salmon", "www.imagen.com/cookedx15", "Nigiri X4");
INSERT INTO products (price, category, description, image, name) VALUES (1400, "rolls", "salmon loin slices", "www.imagen.com/cookedx15", "Sashimi X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "crispy chicken, avocado, swiss cheese, chive, teriyaki sauce, tempura and panko (fried roll)", "www.imagen.com/cookedx15", "California Tori X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "salmon, grilled shrimps, avocado", "www.imagen.com/cookedx15", "Ebi Cream X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "crispy shrimps, avocado, swiss cheese, spicy mayo and flamed salmon", "www.imagen.com/cookedx15", "Koi X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "grilled shrimps, chive, swiss cheese, salmon tartar and lime", "www.imagen.com/cookedx15", "Rock and Roll X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "salmon, grilled shrimps, swiss cheese, tamago", "www.imagen.com/cookedx15", "Finland X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "crispy shrimps, swiss cheese, chive, mustard and honey sauce", "www.imagen.com/cookedx15", "Futurama X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "seaweed, swiss cheese, chive, salmon, guacamole, tempura and panko (fried roll)", "www.imagen.com/cookedx15", "Guacamole Roll X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "tamago, swiss cheese, avocado, salmon, grilled shrimps, caramelized almonds", "www.imagen.com/cookedx15", "Tamago Red X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "rice, grilled shrimps, seaweed, avocado, red tuna, spicy mayo and tare sauce", "www.imagen.com/cookedx15", "Rainbow Roll X4");
INSERT INTO products (price, category, description, image, name) VALUES (1100, "rolls", "seaweed, rice, grilled pepper, swiss cheese, panko and tempura (fried roll)", "www.imagen.com/cookedx15", "Veggie Crunch X4");

INSERT INTO names (firstname, lastname) VALUES ("Carlos", "Nana");
INSERT INTO addresses (number, city, street, zipcode) VALUES (2345, "San Francisco", "Blv. Perón", "12345-12345");
INSERT INTO users (address_id, name_id, email, password, phone, username) VALUES (1 , 1, "carlitos@email.com", "abcedt", "3576-474409", "carlitos1998");


