INSERT INTO product (price, category, description, image, name) VALUES (4000, "combos / salmon", "15 pieces of Sake, Cream Roll, Salmon Maki, Feel Roll", "www.imagen.com/salmonx15", "Full Salmon X15");
INSERT INTO product (price, category, description, image, name) VALUES (7800, "combos / salmon", "30 pieces of Sake, Cream Roll, Salmon Maki, Feel Roll, Tropical, SPF", "www.imagen.com/salmonx30", "Full Salmon X30");
INSERT INTO product (price, category, description, image, name) VALUES (9700, "combos / salmon", "45 pieces of Sake, Cream Roll, Salmon Maki, Feel Roll, Tropical, SPF, Geisha, Nigiri, Sashimi", "www.imagen.com/salmonx45", "Full Salmon X45");
INSERT INTO product (price, category, description, image, name) VALUES (3900, "combos / cooked", "15 pieces of Hot Roll, Poshi, Spicy", "www.imagen.com/cookedx15", "Cooked X15");
INSERT INTO product (price, category, description, image, name) VALUES (7450, "combos / cooked", "30 pieces of Hot Roll, Poshi, Spicy, Ebi", "www.imagen.com/cookedx15", "Cooked X30");
INSERT INTO product (price, category, description, image, name) VALUES (9400, "combos / cooked", "45 pieces of Hot Roll, Poshi, Spicy, Ebi, Kani Roll", "www.imagen.com/cookedx15", "Cooked X45");
INSERT INTO product (price, category, description, image, name) VALUES (6900, "combos / cooked", "25 pieces breaded in Panko and Tempura, includes Poshi, Maki Crazy, Veggie Crunch, California Tori, Guacamole Roll", "www.imagen.com/cookedx15", "Crispy X25");
INSERT INTO product (price, category, description, image, name) VALUES (4000, "combos / veggie", "20 pieces of Pepper Roll, Mango Roll, Maki Veggie, Veggie Crunch", "www.imagen.com/cookedx15", "Veggie X20");
INSERT INTO product (price, category, description, image, name) VALUES (3800, "combos / single", "The Single Combo includes 10 pieces of the chef's choice, 1 Gyoza and a soda", "www.imagen.com/cookedx15", "Single Combo");
INSERT INTO product (price, category, description, image, name) VALUES (7600, "combos / tasting", "30 pieces of Sake, Feel Roll, Tropical Roll, Spicy, Poshi, Hot Roll, Mango Roll, Pepper Roll", "www.imagen.com/cookedx15", "Tasting Combo X30");
INSERT INTO product (price, category, description, image, name) VALUES (9500, "combos / tasting", "45 pieces of Sake, Feel Roll, Tropical Roll, Spicy, Poshi, Hot Roll, Mango Roll, Pepper Roll", "www.imagen.com/cookedx15", "Tasting Combo X45");
INSERT INTO product (price, category, description, image, name) VALUES (7900, "combos / rnr", "30 pieces of Koi, Rock and Roll, Tobiko, Avocado, Hot Roll, Soul, Pepper Roll", "www.imagen.com/cookedx15", "Rock and Roll X30");
INSERT INTO product (price, category, description, image, name) VALUES (10200, "combos / rnr", "45 pieces of Koi, Rock and Roll, Tobiko, Avocado, California Tori, Soul, Ebi Cream, Veggie Crunch, Koi", "www.imagen.com/cookedx15", "Rock and Roll X45");
INSERT INTO product (price, category, description, image, name) VALUES (10200, "combos / premium", "45 pieces of Tobiko, Avocado, Soul, SPF, Maki Crazy", "www.imagen.com/cookedx15", "Premium X45");

